website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required
from flask_wtf import FlaskForm
from sqlalchemy import or_
from . import db
from .models import Boat, CurrentBoats, Visit, User
from .forms import BoatLogForm, PhoneNumber, PublicLogin, SearchForm, PaymentForm, DeleteVisitForm
from .functions import addBoatToDB, get_boat_phone_number, searchBoatInDB, getBoatInDB, updateBoatInfo, getBoatById, add_payment, edit_payment, add_visit, sort_key, remove_visit, calcCurrentBoatStatus,calc_current_time
import re
from datetime import datetime, timezone
from .payment_functions import addBoatToDB as addBoatPublic

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():
    return render_template("home.html")

@views.route('/checkout')
def checkout():
    return render_template('checkout.html')

@views.route('/search', methods=['GET','POST'])
@login_required
def search():
    form = SearchForm()
    if form.validate_on_submit():
        if request.method == "POST":
            button_pressed = request.form.get('submit-button')
            print("Button pressed is: " + str(button_pressed))
            if button_pressed == 'search':
                return searchBoatInDB('search.html', form)
            if button_pressed == 'add':
                return redirect(url_for('views.log_boat', boat_reg=form.boat_reg.data, boat_name=form.boat_name.data, phone_number=form.phone_number.data))
    results = []
    resultsToday = []
    if CurrentBoats.query.first():
        resultsToday = CurrentBoats.query.first().boats.all()
        print(resultsToday)
        for boat in resultsToday:
            calcCurrentBoatStatus(boat)
        #After checks are made and transients are removed
        resultsToday = CurrentBoats.query.first().boats.all()
    return render_template('search.html', form=form, boats=results, currentboats=resultsToday, current_time=calc_current_time())



@views.route('/log-boat', methods=['GET', 'POST'])
@login_required
def log_boat():
    form = BoatLogForm()
    sorted_visits = None
    if form.validate_on_submit():
        if request.method == "POST":
            button_pressed = request.form.get('submit-button')
            print("Button pressed is: " + str(button_pressed))
            if button_pressed == 'log':
                return addBoatToDB('log-boat.html', form)
            elif button_pressed == 'update':
                currentboatID = request.args.get('id', '')
                result = getBoatById(currentboatID)
                updateBoatInfo(form, result)
                flash('Succesfully updated boater information', category='success')
                return redirect(url_for('views.search'))
            elif button_pressed == 'visits':
                currentboatID = request.args.get('id', '')
                boat = getBoatById(currentboatID)
                return redirect(url_for('views.visits', id=currentboatID, boat=boat))
    else:
        print(form.errors)
    if request.method == "GET":
        form.boat_reg.data = boat_reg = request.args.get('boat_reg', '')
        form.boat_name.data = request.args.get('boat_name', '')
        form.phone_number.data = request.args.get('phone_number', '')
        result = getBoatInDB(form)
        print(result)
        if result:
           form.boat_reg.data = result.boat_reg
           form.boat_name.data = result.boat_name
           form.phone_number.data = result.phone_number
           form.boat_size.data = result.boat_size
           form.owner_name.data = result.owner_name
           form.email.data = result.email
           form.zipcode.data = result.zipcode
           if result.visits:
               sorted_visits = sorted(result.visits, key=sort_key, reverse=True)
    return render_template("log-boat.html", form=form, boat=result, visits=sorted_visits)

@views.route('/visits' , methods=['GET','POST'])
@login_required
def visits():
    form = PaymentForm()
    delete_visit_form = DeleteVisitForm()
    button_pressed = request.form.get('submit-button')
    selected_row_id = request.form.get('selectedRowId')
    print("Button pressed is: " + str(button_pressed))
    print("Selected row ID is:", selected_row_id)
    
    boat = getBoatById(request.args.get('id', ''))
    sorted_visits = sorted(boat.visits, key=sort_key, reverse=True)
    if button_pressed == "search":
        form.date_paid.data = calc_current_time()
        form.date_in.data = Visit.query.get(selected_row_id).date_in

    if not boat:
        flash("Bad Boat ID", category='error')
    if request.method == "POST":
        if button_pressed == "delete":
            if delete_visit_form.validate_on_submit():
                remove_visit_id = delete_visit_form.selecteddeleteRowId.data
                print("Remove visit ID:", remove_visit_id)
                remove_visit(remove_visit_id)
            else:
                flash("form invalid" + str(form.errors), category="error")
        else:
            if form.validate_on_submit():
                    if button_pressed == "search":
                        add_payment("visits.html", form, boat, id=selected_row_id)
            elif button_pressed == "add_new":
                form.paid_days.data = "0"
                form.paid_nights.data = "0"
                form.paid_enw.data = None
                print("add new visit")
                add_visit("visits.html", form, boat)
            else:
                flash("form invalid" + str(form.errors), category="error")
    boat = getBoatById(request.args.get('id', ''))
    sorted_visits = sorted(boat.visits, key=sort_key, reverse=True)
    return render_template("visits.html", form=form, boat=boat, visits=sorted_visits, delete_form=delete_visit_form)

@views.route('/update_payment', methods=['POST'])
def update_payment():
    form = PaymentForm(request.form)
    boat = getBoatById(request.args.get('id', ''))
    visitid = request.args.get('visitid', '')
    if form.validate():
        edit_payment(visitid, form)
        return redirect(url_for('views.visits', id=boat.id))
    else:
        print(form.errors)
        flash("Invalid form reload or relogin" + str(form.errors), category="error")
        return redirect(url_for('views.visits', id=boat.id))
    
@views.route('/phone', methods=['POST', 'GET'])
def phone():
    phone_number_Form = PhoneNumber()
    if request.method == "POST":
        if phone_number_Form.validate_on_submit():
            num = phone_number_Form.phone_number.data
            boat = get_boat_phone_number(num)
            print(num)
            if boat is None:
                flash("No boat under that phone number", category='error')
                return render_template("phone.html", form=phone_number_Form , no_render=False)
            elif boat:
                return redirect(url_for('views.public', id=boat.id))
    return render_template("phone.html", form=phone_number_Form, no_render=True)

@views.route('/public_login', methods=['POST', 'GET'])
def public():
    login_form = PublicLogin()
    if request.method == "POST":
        if login_form.validate_on_submit():
            return addBoatPublic(url_for('views.public'), login_form)
    elif request.method == "GET":
        phone_number = request.args.get('phone_number','')
        boat_id = request.args.get('id', '')
        if boat_id != '':
            boat = getBoatById(boat_id)
            login_form.boat_reg.data = boat.boat_reg
            login_form.boat_name.data = boat.boat_name
            login_form.boat_size.data = boat.boat_size
            login_form.phone_number.data = boat.phone_number
            login_form.zipcode.data = boat.zipcode
            login_form.owner_name.data = boat.owner_name
        return render_template("payment.html", form=login_form)

@views.route('/pay', methods=['POST', 'GET'])
def pay():
    phone_number = request.args.get('phone_number')
    boat = get_boat_phone_number(phone_number)
    boat_registration = boat.boat_reg
    boat_size = boat.boat_size
    owner = boat.owner_name
    return render_template('payment.html', phone_number=phone_number, owner=owner, boat_size=boat_size, boat_registration=boat_registration)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.8">
  <title>{%block title%}Gateway Harbor{%endblock%}</title>
  <link rel="stylesheet" href="{%block styles%}static/styles.css{%endblock%}">
  {%block head%}{%endblock%}
</head>
<body>
  <style>
  .fade-out {
  opacity: 0;
  transition: opacity 3s ease-out;
  } 

  </style>
  {%block body%}{%endblock%}
  <div id="content-container">
    <header>
      <h1>{%block header%}Gateway Harbor Sign Up{%endblock%}</h1>
      {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
                <span class="close-btn">&times;</span>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
    </header>
    <div class="container">{% block content %} {% endblock %}</div>
  </div>

  <script>
    var closeBtns = document.getElementsByClassName("close-btn");
    for (var i = 0; i < closeBtns.length; i++) {
      closeBtns[i].addEventListener("click", function() {
        this.parentElement.style.display = 'none';
      });
    }
  
    var alerts = document.querySelectorAll('.alert');
    alerts.forEach(function(alert) {
      if (alert.classList.contains('alert-success')) {
        setTimeout(function() {
          alert.classList.add('fade-out');
          setTimeout(function() {
            alert.style.display = 'none';
          }, 3000); // hide it after 3 seconds of fade-out transition
        }, 1000); // start the fade-out after 3 seconds
      }
    });
  </script>


</body>
</html>

website/templates/cancel.html
{% extends "base.html" %} 
{% block title %}Canceled{% endblock %} 
{%block head%}
{%endblock%}
{%block header%}{%endblock%}
{%block styles%}static/payment-styles.css{%endblock%}
{% block content%}
<style>
    .btn {
        transition: background-color 0.5s ease; /* Increase transition time for smoother effect */
      }
      
      .btn:hover {
        background-color: #009a8a; /* Subtle color change */
      }
      
      /* Fancy load-in animation */
      @keyframes fadeIn {
        from { opacity: 0; transform: translateY(-20px); }
        to { opacity: 1; transform: translateY(0); }
      }
      
      body {
        animation: fadeIn 1s ease-in-out; /* Add slight movement to fade-in */
      }
      
      /* Responsive design */
      @media only screen and (max-width: 768px), (max-width: 480px) {
        .container {
          width: 95%;
          /* Other necessary mobile/tablet adjustments */
        }
        label {
          font-size: 15px; /* Adjust font size for smaller screens */
        }
      }

      h1 {
        color: var(--color5);
        text-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
        font-size: 36px;
        text-align: center;
        margin-top: 20px;
        font-weight: bold;
      }
      
       #total-text {
        color: var(--color2);
        font-size: 24px;
        font-weight: bold;
        text-align: center;
        margin: 10px 0;
      }
      p#total{
        color: var(--color2);
        font-size: 24px;
        text-align: center;
        margin: 10px 0;
      }
      
      ul {
        list-style: none;
        padding: 0;
      }
      
      li {
        padding: 10px;
        background-color: var(--color3);
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
        margin: 10px 0;
      }
      
      li p {
        margin: 5px 0;
      }
      
      li ul {
        margin: 10px;
      }
      
      li ul li {
        background-color: var(--color4);
        padding: 10px;
        border-radius: 5px;
      }
      
      #content-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 95%;
      }

      a {
        text-align: center;
        display: block;
        font-weight: bold;
        font-style: italic;
        color: var(--color2);
        text-decoration: none;
        margin: 20px auto;
        padding: 10px;
        border-radius: 5px;
        width: 30%;
        background-color: var(--color5);
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
      }
      
      a:hover {
        background-color: #047267;
      }

      #link-button{
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      
      .boat-info-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
        background: var(--color3);
        padding: 1.25em;
        margin-bottom: 1.25em;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }
  
    .boat-info-item {
        flex: 1;
        text-align: center;
        margin: 0 0.3125em;
    }
  
    .boat-info-item h3, h2 {
        margin: 0;
        padding-top: 0;
        padding-bottom: 0;
        font-size: 1.125em;
        color: #eeeeee;
        font-weight: normal;
    }
</style>
<h1>Order Canceled</h1>
<p id="total"><span id="total-text">Amount Total:</span> <em>${{ "{:.2f}".format(amount_total / 100) }}</em></p>
{%if boat%}
<p id="total"><span id="total-text">Paid Till:</span> <em>{{ boat.paid_until | utc_to_est_short}}</em></p>
{%endif%}

<div id="boat-info" class="boat-info-container">
    <div class="boat-info-item"><h3><span><b>Reg:</b> </span><em>{{boat.boat_reg}}</em></h3></div>
    <div class="boat-info-item"><h3><span><b>Name:</b> </span><em>{{boat.boat_name}}</em></h3></div>
    <div class="boat-info-item"><h3><span><b>Size:</b> </span><em>{{boat.boat_size}}</em></h3></div>
    <div class="boat-info-item"><h3><span><b>Owner:</b> </span><em>{{boat.owner_name}}</em></h3></div>
    <div class="boat-info-item"><h3><span><b>Phone:</b> </span><em>{{boat.phone_number}}</em></h3></div>
  </div>

<ul>
    {% for item in paid_items %}
    <li>
        <p>Item: {{ item.description }}</p>
        <ul>
            <li>
                <p>Quantity: {{ item.quantity }}</p>
                <p>Item Total: ${{ "{:.2f}".format(item.item_total /100) }}</p>
            </li>
        </ul>
    </li>
    {% endfor %}
</ul>

<div id="link-button">
<a href="{{url_for('views.public')}}">Place Another Order</a>
</div>
{% endblock %}

website/templates/checkout.html
<!DOCTYPE html>
<html>
  <head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="style.css">
    <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body>
    <section>
      <div class="product">
        <img src="https://i.imgur.com/EHyR2nP.png" alt="The cover of Stubborn Attachments" />
        <div class="description">
          <h3>Stubborn Attachments</h3>
          <h5>$20.00</h5>
        </div>
      </div>
      <form action="/create-checkout-session" method="POST">
        <button type="submit" id="checkout-button">Checkout</button>
      </form>
    </section>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block header %}{% endblock %}
{% block styles %}static/home-styles.css{% endblock %}
{% block content %}
<style>
  .large-btn {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
  }
  
  .icon {
    width: 30%; /* Adjust as needed */
    height: auto;
    margin-bottom: 2rem; /* Adjust as needed */
  }
</style>
  <div id="container">
    <a href="{{ url_for('views.search') }}" class="large-btn" id="boatLog">
      <img src="static/magnifier.svg" alt="Search Icon" class="icon"> Search Log
    </a>
    <button class="large-btn">Button 2</button>
    <button class="large-btn">Button 3</button>
    <button class="large-btn">Button 4</button>
    <button class="large-btn">Button 5</button>
    <button class="large-btn">Button 6</button>
  </div>
{% endblock %}

website/templates/log-boat.html
{% extends "base.html" %} 
{% block title %}Log Boat{% endblock %} 
{%block header%}
{%endblock%}
{%block body%}
{%endblock%}
{%block styles%}static/form-styles.css{%endblock%}
{% block content%}
<style>
.info-container{
    background-color: #393e46;
    border-radius: 10px;
    padding: 0.5em;
}
.form-control{
    background-color: #4E535A;
}
.title-log-boat{
    display: flex;
    align-items: center;
}
.title-log-boat h1{
    padding-left: 1.25em;
}
#home-btn{
    font-size: 1.5em;
    padding: 0.5em;
}
.back-button-container{
    padding: 2em;
}

.visit-info-container{
    background-color: #393e46;
    border-radius: 10px;
    padding: 0.5em;
    margin-bottom: 0.8em;
}
.visit-info-item h3, h2 {
    font-size: 1.125em;
    color: #eeeeee;
    font-weight: normal;
    margin-top: 0.3em;
}
h3.last-visit{
    font-size: 2em;
    color: #eeeeee;
}
.paid-times{
    display:inline-flex;
    justify-content: center;
    padding: 0;
    margin: 0;
}
.paid-times h3{
    padding-left: 0.5em;
    padding-right: 0.5em;
}
.red-tint {
    background-color: rgba(255, 0, 0, 0.2) !important;
}
.yellow-tint {
    background-color: rgba(251, 255, 20, 0.3) !important;
}
.unpaid-total h3, .last-payment h3 , .last-visit h3{
    margin-bottom: 0;
}
.red-tint-text{
    color: rgba(255, 0, 0, 1) !important;
}
.yellow-tint-text{
    color: rgb(255, 244, 28) !important;
}
</style>
<div class="title-log-boat">
    <a href="{{ url_for('views.search') }}"id="home-btn">Back</a>
    <h1>Log Boat</h1>
</div>
{% if not visits == None %} 
<div class="visit-info-container {% if not boat.total_unpaid_nights == None and boat.total_unpaid_nights > 0 %}red-tint{%elif not boat.total_unpaid_days == None and boat.total_unpaid_days > 0%} yellow-tint {% endif %}"">
    <div class="visit-info-item last-visit"><h3><span><b>Last Visit:</b> </span><em>{{visits[0].date_in | utc_to_est_short}}</em></h3></div>
    {% if not visits[0].date_paid == None %} 
    <div class="visit-info-item last-payment"><h3><span><b>Last Payment:</b> </span><em>{{visits[0].date_paid | utc_to_est_short}}</em></h3></div>
    <div class="visit-info-item last-payment"><h3><span><b>Paid Until:</b> </span><em>{{boat.paid_until | utc_to_est_short}}</em></h3></div>
    <div class="paid-times">
        <div class="visit-info-item"><h3><span><b>Paid days:</b> </span><em>{{visits[0].paid_days }}</em></h3></div>
        <div class="visit-info-item"><h3><span><b>Paid nights:</b> </span><em>{{visits[0].paid_nights}}</em></h3></div>
    </div>
    {%endif%}
    {% if not visits[0].unpaid_total == None and visits[0].unpaid_total < 0 %}
    <div class="visit-info-item unpaid-total"><h3><span><b>Unpaid total:</b> </span><em>${{visits[0].unpaid_total }}0</em></h3></div>
    <div class="paid-times">
        <div class="visit-info-item"><h3><span><b><u>Total unpaid days:</u></b> </span><em >{{boat.total_unpaid_days }}</em></h3></div>
        <div class="visit-info-item"><h3><span><b><u>Total unpaid nights:</u></b> </span><em>{{boat.total_unpaid_nights }}</em></h3></div>
    </div>
    {%endif%}
</div>
{%endif%}
<div class="info-container">
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.boat_reg.label }}
            {{ form.boat_reg(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.boat_name.label }}
            {{ form.boat_name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.boat_size.label }}
        <div>
            {% for subfield in form.boat_size %}
                {{ subfield(class="form-check-input") }} {{ subfield.label(class="form-check-label") }}
            {% endfor %}
        </div>
        </div>
    
        
        <div class="form-group">
            {{ form.owner_name.label }}
            {{ form.owner_name(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.phone_number.label }}
            {{ form.phone_number(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.email.label }}
            {{ form.email(class="form-control") }}
        </div>
        <div class="form-group">
            {{ form.zipcode.label }}
            {{ form.zipcode(class="form-control") }}
        </div>
        {% if boat == None or not boat.current_boats_id %}
            <button type="submit" class="btn btn-primary" id="login-btn" name="submit-button" value="log">Log Boat</button>
        {% else %}
            <button type="submit" class="btn btn-primary" id="update-btn" name="submit-button" value="update">Update Only Info.</button>
        {% endif %}
        <button type="submit" class="btn btn-primary" id="update-btn" name="submit-button" value="visits">Visits</button>
          
    </form>
</div>
{%endblock%}

website/templates/public-login.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block header %}{% endblock %}
{% block styles %}static/home-styles.css{% endblock %}
{% block content %}
{% endblock %}

website/templates/search.html
{% extends "base.html" %} 
{% block title %}Search Boats{% endblock %} 
{%block head%}
<a href="{{ url_for('views.home') }}"id="home-btn">Home</a>
{%endblock%}
{%block header%}{%endblock%}
{%block styles%}static/search-styles.css{%endblock%}
{% block content%}
<style>
  .red-tint {
    background-color: rgba(255, 0, 0, 0.2) !important;
  }
  .yellow-tint {
      background-color: rgba(251, 255, 20, 0.3) !important;
  }
  .green-tint {
    background-color: rgba(0, 255, 38, 0.294) !important;
}
  .form-group {
    margin-bottom: 1em;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  .form-group label {
    display: block;
    color: #eeeeee;
  }
  
  .form-group div {
    display: flex;
    justify-content: space-between;
  }
  
  .form-check-input, .form-check-label {
    display: inline-block;
    margin-right: 0.625em;
  }
  
  .form-check-input {
    width: auto;
    height: auto;
  }
  
  input[type='radio'] {
    width: 1.5625em; 
    height: 1.5625em;
  }
  
  .form-group input {
    width: 100%;
    padding: 0.625em;
    border: none;
    border-radius: 5px;
  }
  
  .form-control {
    background-color: #393e46;
    color: #eeeeee;
  }
  
  .form-control::placeholder {
    color: #adb5bd;
  }
  
  .form-control:focus {
    outline: none;
    box-shadow: 0 0 0 0.2rem rgba(0, 173, 181, 0.25);
  }
  
  .btn-primary, #update-btn {
    font-size: 1.5em;
    background-color: #00adb5;
    margin: auto;
    color: #eeeeee;
    padding: 1.25em 2.5em;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease, transform 0.3s ease;
    border-radius: 5px;
    margin-bottom: 1.25em;
  }
  
  .btn-primary:hover, #update-btn:hover {
    background-color: #009e9a;
    transform: scale(1.05);
  }
  
  .btn-primary:active, #update-btn:active {
    background-color: #00756e;
  }
  
  #update-btn {
    font-size: 0.9375em;
    background-color: #DF740C;
  }
  #home-btn {
    font-size: 1.125em;
    background-color: #00adb5;
    color: #eeeeee;
    padding: 0.625em 0.9375em;
    border: none;
    cursor: pointer;
    text-decoration: none;
    transition: background-color 0.3s ease, transform 0.3s ease;
    border-radius: 5px;
    display: inline-block;
    margin-right: 0.3125em;
  }
  
  #home-btn:hover {
    background-color: #009e9a;
    transform: scale(1.05);
  }
  
  #home-btn:active {
    background-color: #00756e;
  }
  
  @keyframes fadein {
      from { opacity: 0; }
      to   { opacity: 1; }
  }



  #search-container {
    width: 100%; 
    display: flex;
    justify-content: center;
    align-items: center;
  }
  #search-container form {
    align-items: center;
    padding: 5px;
    border-radius: 5px;
    background-color: rgb(57, 62, 70);
  }
  #search-container input {
    background-color:#4E535A;
  }
  #content-container{
    flex-direction: column;
    align-items: center;
  }
  #table-no-header{
    height: 20em; 
    border-radius: 5px;
    overflow-y: auto;
    background-color: #393e46;
  }
  table {
    border-collapse: collapse;
  }
  #left-container{ 
    display:inline-block;
    align-items: center;
  }
  #right-container #table-no-header{
    height: 30em; 
  }
</style>
<div id="main-container">
  
  <div id="left-container" style="flex: 1;">
    <div id="search-container">
      <form method="POST" id="search">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{ form.boat_reg.label }}
          {{ form.boat_reg(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.boat_name.label }}
          {{ form.boat_name(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.phone_number.label }}
          {{ form.phone_number(class="form-control") }}
        </div>
        <div id="button-container">
          <button type="submit" class="btn btn-primary" id="login-btn" name="submit-button" value="search">Search</button>
        </div>
      </form>
    </div>

    <div id="table-container">
      <h2>From Database</h2>
      <div id="table-no-header">
        <table id="search-results">
          <thead>
            <tr>
              <th>Boat Reg.</th>
              <th>Phone Number</th>
              <th>Boat Name</th>
            </tr>
          </thead>
          <tbody>
            {% for boat in boats %}
            <tr class="clickable-row {% if not boat.total_unpaid_nights == None and boat.total_unpaid_nights > 0 %}red-tint{%elif not boat.total_unpaid_days == None and boat.total_unpaid_days > 0%} yellow-tint {%elif boat | has_paid %}green-tint{% endif %}" data-href="{{ url_for('views.log_boat', boat_reg=boat.boat_reg, boat_name=boat.boat_name, phone_number=boat.phone_number,  id=boat.id) }}">
              <td>{{ boat.boat_reg }}</td>
              <td>{{ boat.phone_number }}</td>
              <td>{{ boat.boat_name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
    </div>
  </div>


  <div id="right-container" style="flex: 1;">
    <div id="table-container">
      <h2>Today</h2>
      {%if currentboats%}
      <div id="table-no-header">
        <table id="current-boats">
          <thead>
            <tr>
              <th>Boat Reg.</th>
              <th>Phone Number</th>
              <th>Boat Name</th>
            </tr>
          </thead>
          <tbody>
            {% for boat in currentboats %}
            <tr class="clickable-row {% if not boat.total_unpaid_nights == None and boat.total_unpaid_nights > 0 %}red-tint{%elif not boat.total_unpaid_days == None and boat.total_unpaid_days > 0%} yellow-tint {%elif boat | has_paid %}green-tint{% endif %}" data-href="{{ url_for('views.log_boat', boat_reg=boat.boat_reg, boat_name=boat.boat_name, phone_number=boat.phone_number,  id=boat.id) }}">
              <td>{{ boat.boat_reg }}</td>
              <td>{{ boat.phone_number }}</td>
              <td>{{ boat.boat_name }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
      <div id="button-container">
            <button type="submit" form="search" class="btn btn-primary" id="login-btn" name="submit-button" value="add">Add New Boat</button>
      </div>
      {%endif%}
    </div>
  </div>
</div>
  <script src="{{ url_for('static', filename='js/search.js') }}"></script>
  <script>
    window.onload = function() {
      const rows = document.querySelectorAll('.clickable-row');
      rows.forEach(row => {
        row.addEventListener('click', () => {
          window.location.href = row.getAttribute('data-href');
        });
      });
    };
  </script>
  
{%endblock%}